version: '3.4'

services:
  kitsuunban:
    image: kitsuunban
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "App/index.ts"]
