version: '3.4'

services:
  kitsu-moderator-bot:
    image: kitsu-moderator-bot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file:
      - .env
